apiVersion: apps/v1
kind: Deployment
metadata:
  name: taxiapp
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taxiapp
  template:
    metadata:
      labels:
        app: taxiapp
    spec:
      imagePullSecrets:
        - name: jfrog-cred
      containers:
        - name: taxiapp
          image: taxibooking01.jfrog.io/taxi-dev-docker-local/taxiapp:IMAGE_TAG
          ports:
            - containerPort: 8080
