apiVersion: v1
kind: Service
metadata:
  name: taxiapp-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: taxiapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
